name: plantcare
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  icons_plus: ^5.0.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.4
  flutter_facebook_auth: ^7.1.2
  another_flushbar: ^1.10.30
  shared_preferences: ^2.5.3
  flutter_bloc: ^8.1.3
  http: ^1.2.2
  image_picker: ^1.0.4
  equatable: ^2.0.5
  camera: ^0.10.5+5
  cloud_firestore: ^5.6.10
  intl: ^0.18.1
  path_provider: ^2.1.1
  webview_flutter: ^4.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1 
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/plant.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
